name: Build & Test

on: [push, pull_request]

jobs:

  build:
    name: Build, Test & Run Tutorials
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Do it
      run: scripts/ci-build

