name: Deploy Pages

on:
  push:
    branches: [ master ]
    paths:
    - 'src/handbook/**'

jobs:

  build:
    name: Build & Deploy Pages
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Handbook dependencies
      run: sudo apt-get -y install inkscape

    - name: Do it
      run: scripts/ci-deploy

    - name: Deploy to the gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

